apiVersion: "v1"
kind: Pod
metadata:
      name: player-mongo # db pod name
      labels:
        name: player-mongo
spec:
  containers:
      - image: mongo
        name: mongo
        ports:
          - containerPort: 27017
            name: mongo
        volumeMounts:
          - mountPath: "/data/db/"
            name: player-pv-storage
  volumes:
    - name: player-pv-storage
      persistentVolumeClaim:
       claimName: player-pv-claim